name: Push Event Activity

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths-ignore:
      - 'doc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print build
        run: echo 'build for push filter activity'
