name: Python setup

on: 
  workflow_dispatch
jobs:
  node-js:
    runs-on: ubuntu-latest
    steps:
      - name: setup python environment
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3
      - run: python --version
